In [1]:
#对house表进行数据统计，得出租房全览所需的watch0,watch1,watch2表
import numpy as np
import pandas as pd
import pymysql
conn = pymysql.connect(
    host='localhost',
    user='root',
    password='123456789',
    database='house_datas',
    charset='utf8'
)
df = pd.read_sql('select * from house',conn)
df

,houseId,city,dist,flag,title,address,price,size,direction,style,floor,resource,time,tag,href,pic,reality
0,1,2,罗湖区,整租,清水河生活小区1室1厅南,罗湖区-清水河-清水河生活小区,1900.0,40.0,南,1室1厅1卫,中楼层（7层）,,今天维护,官方核验新上近地铁随时看房,https://bj.lianjia.com//zufang/SZ2526578748351...,https://ke-image.ljcdn.com/110000-inspection/c...,47.5000
1,2,2,龙华区,整租,创业花园1室0厅南,龙华区-红山-创业花园,1350.0,20.0,南,1室0厅1卫,中楼层（16层）,星窝青年创业公寓,今天维护,新上租住保障公寓月租近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2524557529225...,https://ke-image.ljcdn.com/rent-user-avatar/13...,67.5000
2,3,2,南山区,整租,前海花园3室0厅南,南山区-前海-前海花园,2100.0,90.0,南,3室0厅0卫,中楼层（7层）,链家,今天维护,官方核验新上近地铁随时看房,https://bj.lianjia.com//zufang/SZ2524009212502...,https://ke-image.ljcdn.com/110000-inspection/8...,23.3333
3,4,2,龙华区,整租,共和花园1室1厅南,龙华区-龙华中心-共和花园,1214.0,30.0,南,1室1厅1卫,高楼层（4层）,星寓,1天前维护,新上公寓月租精装押一付一随时看房,https://bj.lianjia.com//zufang/SZ2527322525981...,https://ke-image.ljcdn.com/rent-user-avatar/58...,40.4667
4,5,2,福田区,整租,城市3米6公寓1室0厅南,福田区-福田保税区-城市3米6公寓,2000.0,16.0,南,1室0厅1卫,中楼层（27层）,链家,2天前维护,官方核验新上随时看房,https://bj.lianjia.com//zufang/SZ2525874272422...,https://ke-image.ljcdn.com/110000-inspection/0...,125.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18082,32995,2,龙岗区,整租,德福花园1室1厅西,龙岗区-布吉街-德福花园,2300.0,42.0,西,1室1厅1卫,低楼层（19层）,链家,10天前维护,官方核验随时看房,https://bj.lianjia.com//zufang/SZ2478161060025...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,54.7619
18083,32996,2,大鹏新区,整租,承翰半山海1室1厅南,大鹏新区-大鹏半岛-承翰半山海,2200.0,37.0,南,1室1厅1卫,中楼层（12层）,链家,6天前维护,官方核验精装,https://bj.lianjia.com//zufang/SZ2298573259765...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,59.4595
18084,33004,2,罗湖区,整租,华商时代公寓1室1厅东,罗湖区-笋岗-华商时代公寓,3600.0,42.0,东,1室1厅1卫,中楼层（19层）,链家,13天前维护,官方核验随时看房,https://bj.lianjia.com//zufang/SZ2508097554769...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,85.7143
18085,33005,2,宝安区,合租,碧海富通城六期5居室北卧,宝安区-碧海-碧海富通城六期,1760.0,10.0,北,5室1厅2卫,高楼层（30层）,自如,今天维护,公寓近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2113776953772...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,176.0000
18086,33009,2,福田区,合租,香珠花园4居室北卧,福田区-香蜜湖-香珠花园,2430.0,11.0,北,4室1厅2卫,低楼层（9层）,自如,今天维护,公寓近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2176107620123...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,220.9090

In [2]:
# 拷贝一份数据，不对原始数据进行修改
df1 = df.copy()
df1

,houseId,city,dist,flag,title,address,price,size,direction,style,floor,resource,time,tag,href,pic,reality
0,1,2,罗湖区,整租,清水河生活小区1室1厅南,罗湖区-清水河-清水河生活小区,1900.0,40.0,南,1室1厅1卫,中楼层（7层）,,今天维护,官方核验新上近地铁随时看房,https://bj.lianjia.com//zufang/SZ2526578748351...,https://ke-image.ljcdn.com/110000-inspection/c...,47.5000
1,2,2,龙华区,整租,创业花园1室0厅南,龙华区-红山-创业花园,1350.0,20.0,南,1室0厅1卫,中楼层（16层）,星窝青年创业公寓,今天维护,新上租住保障公寓月租近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2524557529225...,https://ke-image.ljcdn.com/rent-user-avatar/13...,67.5000
2,3,2,南山区,整租,前海花园3室0厅南,南山区-前海-前海花园,2100.0,90.0,南,3室0厅0卫,中楼层（7层）,链家,今天维护,官方核验新上近地铁随时看房,https://bj.lianjia.com//zufang/SZ2524009212502...,https://ke-image.ljcdn.com/110000-inspection/8...,23.3333
3,4,2,龙华区,整租,共和花园1室1厅南,龙华区-龙华中心-共和花园,1214.0,30.0,南,1室1厅1卫,高楼层（4层）,星寓,1天前维护,新上公寓月租精装押一付一随时看房,https://bj.lianjia.com//zufang/SZ2527322525981...,https://ke-image.ljcdn.com/rent-user-avatar/58...,40.4667
4,5,2,福田区,整租,城市3米6公寓1室0厅南,福田区-福田保税区-城市3米6公寓,2000.0,16.0,南,1室0厅1卫,中楼层（27层）,链家,2天前维护,官方核验新上随时看房,https://bj.lianjia.com//zufang/SZ2525874272422...,https://ke-image.ljcdn.com/110000-inspection/0...,125.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18082,32995,2,龙岗区,整租,德福花园1室1厅西,龙岗区-布吉街-德福花园,2300.0,42.0,西,1室1厅1卫,低楼层（19层）,链家,10天前维护,官方核验随时看房,https://bj.lianjia.com//zufang/SZ2478161060025...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,54.7619
18083,32996,2,大鹏新区,整租,承翰半山海1室1厅南,大鹏新区-大鹏半岛-承翰半山海,2200.0,37.0,南,1室1厅1卫,中楼层（12层）,链家,6天前维护,官方核验精装,https://bj.lianjia.com//zufang/SZ2298573259765...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,59.4595
18084,33004,2,罗湖区,整租,华商时代公寓1室1厅东,罗湖区-笋岗-华商时代公寓,3600.0,42.0,东,1室1厅1卫,中楼层（19层）,链家,13天前维护,官方核验随时看房,https://bj.lianjia.com//zufang/SZ2508097554769...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,85.7143
18085,33005,2,宝安区,合租,碧海富通城六期5居室北卧,宝安区-碧海-碧海富通城六期,1760.0,10.0,北,5室1厅2卫,高楼层（30层）,自如,今天维护,公寓近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2113776953772...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,176.0000
18086,33009,2,福田区,合租,香珠花园4居室北卧,福田区-香蜜湖-香珠花园,2430.0,11.0,北,4室1厅2卫,低楼层（9层）,自如,今天维护,公寓近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2176107620123...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,220.9090

In [3]:
#筛选出独栋数据，独栋无地区信息
df2 = df1.loc[df1['flag'] == '独栋']
df2

,houseId,city,dist,flag,title,address,price,size,direction,style,floor,resource,time,tag,href,pic,reality
4269,6005,1,26,独栋,友联华宸酒店式公寓复旦大学店大床房开间,26-30㎡,2600.0,26.0,1室0厅1卫,None,None,友联华宸酒店式公寓,5天前维护,独栋公寓月租押一付一,https://bj.lianjia.com//apartment/28721.html,https://ke-image.ljcdn.com/rent-user-avatar/b8...,100.0000
4271,6007,1,59,独栋,华润置地,59-73㎡,8351.0,59.0,1室1厅1卫,None,None,华润置地·有巢公寓,3个月前维护,独栋公寓月租近地铁开放厨房,https://bj.lianjia.com//apartment/18630.html,https://ke-image.ljcdn.com/rent-user-avatar/54...,141.5420
4273,6009,1,45㎡,独栋,华润置地,45㎡,4280.0,45.0,1室0厅1卫,None,None,华润置地·有巢公寓,今天维护,独栋公寓月租近地铁开放厨房押一付一,https://bj.lianjia.com//apartment/18630.html,https://ke-image.ljcdn.com/rent-user-avatar/88...,95.1111
6809,9009,0,仅剩1间,独栋,乐乎城市青年社区乐乎公寓西二旗社区工业风1室1厅,仅剩1间,5500.0,50.0,1间在租,1室1厅1卫,None,乐乎城市青年社区,今天维护,新上独栋公寓近地铁开放厨房押一付一,https://bj.lianjia.com//apartment/29382.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,110.0000
6810,9010,0,仅剩2间,独栋,乐乎城市青年社区乐乎有朋双合店五月特价房1室1厅,仅剩2间,2000.0,20.0,2间在租,1室1厅1卫,None,乐乎城市青年社区,今天维护,新上独栋公寓开放厨房,https://bj.lianjia.com//apartment/24391.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,100.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14408,23959,2,15,独栋,ZOME己美,15-18㎡,800.0,19.0,1室0厅1卫,1室0厅1卫,None,ZOME己美·严选,4天前维护,新上独栋公寓月租近地铁,https://bj.lianjia.com//apartment/30466.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,42.1053
14410,23961,2,仅剩1间,独栋,恬心公寓恬心公寓杨屋村17号店阳台大单间开间,仅剩1间,1100.0,22.0,1间在租,1室0厅1卫,None,恬心公寓,4天前维护,新上独栋公寓月租有阳台开放厨房押一付一,https://bj.lianjia.com//apartment/14112.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,50.0000
14412,23963,2,仅剩1间,独栋,平台优选商家瓜地新村73栋龙胜地铁站附近。特价开间,仅剩1间,900.0,18.0,1间在租,1室0厅1卫,None,平台优选商家,4天前维护,新上独栋公寓月租有阳台开放厨房,https://bj.lianjia.com//apartment/30465.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,50.0000
14413,23964,2,仅剩1间,独栋,恬心公寓恬心公寓杨屋村17号店大单间开间,仅剩1间,950.0,20.0,1间在租,1室0厅1卫,None,恬心公寓,4天前维护,新上独栋公寓月租开放厨房,https://bj.lianjia.com//apartment/14112.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,47.5000
14415,23966,2,仅剩1间,独栋,恬心公寓恬心公寓杨屋村17号店标准单间开间,仅剩1间,850.0,15.0,1间在租,1室0厅1卫,None,恬心公寓,4天前维护,新上独栋公寓月租开放厨房,https://bj.lianjia.com//apartment/14112.html,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,56.6667

In [4]:
# 有地区信息
df3 = df1.loc[df1['flag'] != '独栋']
df3

,houseId,city,dist,flag,title,address,price,size,direction,style,floor,resource,time,tag,href,pic,reality
0,1,2,罗湖区,整租,清水河生活小区1室1厅南,罗湖区-清水河-清水河生活小区,1900.0,40.0,南,1室1厅1卫,中楼层（7层）,,今天维护,官方核验新上近地铁随时看房,https://bj.lianjia.com//zufang/SZ2526578748351...,https://ke-image.ljcdn.com/110000-inspection/c...,47.5000
1,2,2,龙华区,整租,创业花园1室0厅南,龙华区-红山-创业花园,1350.0,20.0,南,1室0厅1卫,中楼层（16层）,星窝青年创业公寓,今天维护,新上租住保障公寓月租近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2524557529225...,https://ke-image.ljcdn.com/rent-user-avatar/13...,67.5000
2,3,2,南山区,整租,前海花园3室0厅南,南山区-前海-前海花园,2100.0,90.0,南,3室0厅0卫,中楼层（7层）,链家,今天维护,官方核验新上近地铁随时看房,https://bj.lianjia.com//zufang/SZ2524009212502...,https://ke-image.ljcdn.com/110000-inspection/8...,23.3333
3,4,2,龙华区,整租,共和花园1室1厅南,龙华区-龙华中心-共和花园,1214.0,30.0,南,1室1厅1卫,高楼层（4层）,星寓,1天前维护,新上公寓月租精装押一付一随时看房,https://bj.lianjia.com//zufang/SZ2527322525981...,https://ke-image.ljcdn.com/rent-user-avatar/58...,40.4667
4,5,2,福田区,整租,城市3米6公寓1室0厅南,福田区-福田保税区-城市3米6公寓,2000.0,16.0,南,1室0厅1卫,中楼层（27层）,链家,2天前维护,官方核验新上随时看房,https://bj.lianjia.com//zufang/SZ2525874272422...,https://ke-image.ljcdn.com/110000-inspection/0...,125.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18082,32995,2,龙岗区,整租,德福花园1室1厅西,龙岗区-布吉街-德福花园,2300.0,42.0,西,1室1厅1卫,低楼层（19层）,链家,10天前维护,官方核验随时看房,https://bj.lianjia.com//zufang/SZ2478161060025...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,54.7619
18083,32996,2,大鹏新区,整租,承翰半山海1室1厅南,大鹏新区-大鹏半岛-承翰半山海,2200.0,37.0,南,1室1厅1卫,中楼层（12层）,链家,6天前维护,官方核验精装,https://bj.lianjia.com//zufang/SZ2298573259765...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,59.4595
18084,33004,2,罗湖区,整租,华商时代公寓1室1厅东,罗湖区-笋岗-华商时代公寓,3600.0,42.0,东,1室1厅1卫,中楼层（19层）,链家,13天前维护,官方核验随时看房,https://bj.lianjia.com//zufang/SZ2508097554769...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,85.7143
18085,33005,2,宝安区,合租,碧海富通城六期5居室北卧,宝安区-碧海-碧海富通城六期,1760.0,10.0,北,5室1厅2卫,高楼层（30层）,自如,今天维护,公寓近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2113776953772...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,176.0000
18086,33009,2,福田区,合租,香珠花园4居室北卧,福田区-香蜜湖-香珠花园,2430.0,11.0,北,4室1厅2卫,低楼层（9层）,自如,今天维护,公寓近地铁精装随时看房,https://bj.lianjia.com//zufang/SZ2176107620123...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,220.9090

In [5]:
#筛选出北京的数据
city0 = df3.loc[df3['city'] == '0']
city0

,houseId,city,dist,flag,title,address,price,size,direction,style,floor,resource,time,tag,href,pic,reality
2389,3004,0,朝阳,整租,金台里1室1厅北,朝阳-红庙-金台里,5200.0,40.0,北,1室1厅1卫,中楼层（5层）,链家,今天维护,业主自荐新上近地铁精装集中供暖随时看房,https://bj.lianjia.com//zufang/BJ2523221751698...,https://ke-image.ljcdn.com/110000-inspection/p...,130.0000
2390,3005,0,朝阳,整租,金都心语1室1厅东,朝阳-百子湾-金都心语,5990.0,50.0,东,1室1厅1卫,低楼层（21层）,自如,今天维护,公寓月租近地铁精装集中供暖押一付一随时看房,https://bj.lianjia.com//zufang/BJ2220872660861...,https://ke-image.ljcdn.com/rent-house-1/2b6594...,119.8000
2391,3006,0,亦庄开发区,整租,宏仁家园2室1厅南,亦庄开发区-马驹桥-宏仁家园,3400.0,89.0,南,2室1厅1卫,中楼层（28层）,链家,今天维护,业主自荐新上集中供暖,https://bj.lianjia.com//zufang/BJ2525873332051...,https://ke-image.ljcdn.com/110000-inspection/6...,38.2022
2392,3007,0,房山,整租,旭辉E天地1室1厅北,房山-良乡-旭辉E天地,3160.0,36.0,北,1室1厅1卫,中楼层（14层）,自如,今天维护,公寓近地铁精装集中供暖押一付一随时看房,https://bj.lianjia.com//zufang/BJ2388133382833...,https://ke-image.ljcdn.com/rent-house-1/2b6594...,87.7778
2393,3008,0,朝阳,整租,周庄嘉园6号院1室1厅南,朝阳-十里河-周庄嘉园6号院,4700.0,56.0,南,1室1厅1卫,低楼层（28层）,链家,今天维护,新上集中供暖,https://bj.lianjia.com//zufang/BJ2526603674973...,https://ke-image.ljcdn.com/110000-inspection/0...,83.9286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15818,27002,0,东城,整租,安乐林二条1室1厅南,东城-永定门-安乐林二条,4100.0,41.0,南,1室1厅1卫,中楼层（6层）,链家,今天维护,近地铁精装集中供暖,https://bj.lianjia.com//zufang/BJ2512062606349...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,100.0000
15819,27003,0,丰台,整租,大瓦窑绿洲家园1室1厅南/北,丰台-青塔-大瓦窑绿洲家园,3900.0,66.0,南北,1室1厅1卫,中楼层（28层）,链家,今天维护,近地铁随时看房,https://bj.lianjia.com//zufang/BJ2497803251634...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,59.0909
15820,27004,0,朝阳,整租,聚福苑1室1厅南,朝阳-定福庄-聚福苑,5000.0,60.0,南,1室1厅1卫,高楼层（11层）,链家,4天前维护,近地铁精装,https://bj.lianjia.com//zufang/BJ2505863130756...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,83.3333
15821,27005,0,朝阳,整租,定福庄西街1室1厅西,朝阳-定福庄-定福庄西街,4500.0,56.0,西,1室1厅1卫,高楼层（18层）,链家,今天维护,近地铁集中供暖,https://bj.lianjia.com//zufang/BJ2410628797872...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,80.3571
15822,27006,0,朝阳,整租,松榆西里1室1厅西,朝阳-潘家园-松榆西里,4800.0,46.0,西,1室1厅1卫,高楼层（20层）,链家,今天维护,近地铁集中供暖随时看房,https://bj.lianjia.com//zufang/BJ2512907248729...,https://s1.ljcdn.com/matrix_pc/dist/pc/src/res...,104.3480

In [8]:
# count()统计数量，
# sort_values(ascending=True)升序排列
# to_frame()将series转换为dataframe
# count字段
house_count = city0.groupby('dist')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
house_count = house_count.reset_index().rename({'dist':'dist','reality':'count'},axis=1).set_index('dist')
#按地区排序，方便合并
house_count.sort_values("dist",inplace=True)
house_count

       count
dist
东城       305
丰台       587
亦庄开发区    131
大兴       428
房山       214
昌平       263
朝阳      1492
海淀       468
石景山      164
西城       295
通州       334
门头沟      126
顺义       499

In [9]:
#每平米单价字段，按地区排序
mean_house = city0.groupby('dist')['reality'].mean().to_frame().reset_index().rename({'dist':'dist','reality':'perprice'},axis=1).set_index('dist')
mean_house.sort_values("dist",inplace=True)
mean_house

         perprice
dist
东城     125.119949
丰台      94.281691
亦庄开发区   73.458337
大兴      80.267987
房山      54.910599
昌平     105.605065
朝阳     101.954125
海淀     117.071187
石景山    100.656716
西城     126.795251
通州     103.603439
门头沟     70.065987
顺义      56.309875

In [10]:
#合并两表的值
house_count['perprice'] = mean_house['perprice']
#将dist作为列字段
house_count['dist'] = house_count.index

In [11]:
#添加city字段
house_count['city'] = '0'
house_count #得到北京地区信息

       count    perprice   dist city
dist
东城       305  125.119949     东城    0
丰台       587   94.281691     丰台    0
亦庄开发区    131   73.458337  亦庄开发区    0
大兴       428   80.267987     大兴    0
房山       214   54.910599     房山    0
昌平       263  105.605065     昌平    0
朝阳      1492  101.954125     朝阳    0
海淀       468  117.071187     海淀    0
石景山      164  100.656716    石景山    0
西城       295  126.795251     西城    0
通州       334  103.603439     通州    0
门头沟      126   70.065987    门头沟    0
顺义       499   56.309875     顺义    0

In [12]:
#重复上述步骤得到上海的数据
#筛选出上海的数据
city1 = df3.loc[df1['city'] == '1']
city1.head()

,houseId,city,dist,flag,title,address,price,size,direction,style,floor,resource,time,tag,href,pic,reality
4268,6004,1,徐汇,整租,苑宏新村2室0厅南,徐汇-徐汇滨江-苑宏新村,3800.0,51.0,南,2室0厅1卫,高楼层（6层）,贝壳优选,1天前维护,新上随时看房,https://bj.lianjia.com//zufang/SH2378975384021...,https://ke-image.ljcdn.com/lease-image/house/7...,74.5098
4270,6006,1,长宁,整租,新泾四村1室1厅南,长宁-北新泾-新泾四村,4400.0,40.0,南,1室1厅1卫,中楼层（6层）,贝壳优选,1天前维护,新上近地铁随时看房,https://bj.lianjia.com//zufang/SH2410807004965...,https://ke-image.ljcdn.com/lease-image/house/7...,110.0000
4272,6008,1,长宁,整租,清宁小区1室1厅南,长宁-中山公园-清宁小区,4600.0,34.0,南,1室1厅1卫,中楼层（7层）,贝壳优选,15天前维护,随时看房,https://bj.lianjia.com//zufang/SH2515878452335...,https://ke-image.ljcdn.com/lease-image/house/a...,135.2940
4274,6010,1,长宁,整租,虹霞小区1室0厅南,长宁-仙霞-虹霞小区,4300.0,33.0,南,1室0厅1卫,高楼层（6层）,贝壳优选,3天前维护,近地铁随时看房,https://bj.lianjia.com//zufang/SH2397578970154...,https://ke-image.ljcdn.com/lease-image/house/a...,130.3030
4275,6011,1,静安,整租,愚谷村1室1厅北,静安-静安寺-愚谷村,4600.0,25.0,北,1室1厅1卫,高楼层（3层）,贝壳优选,今天维护,新上近地铁精装随时看房,https://bj.lianjia.com//zufang/SH2383255193204...,https://ke-image.ljcdn.com/lease-image/house/c...,184.0000

In [13]:
# count字段
house_count1 = city1.groupby('dist')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
house_count1 = house_count1.reset_index().rename({'dist':'dist','reality':'count'},axis=1).set_index('dist')
house_count1

      count
dist
金山        2
虹口      155
奉贤      178
嘉定      186
松江      187
青浦      206
宝山      223
杨浦      262
黄浦      348
普陀      358
静安      557
闵行      666
长宁      764
徐汇      992
浦东     1657

In [14]:
#按地区排序，方便合并
house_count1.sort_values("dist",inplace=True)
house_count1

      count
dist
嘉定      186
奉贤      178
宝山      223
徐汇      992
普陀      358
杨浦      262
松江      187
浦东     1657
虹口      155
金山        2
长宁      764
闵行      666
青浦      206
静安      557
黄浦      348

In [15]:
#每平米单价字段
mean_house1 = city1.groupby('dist')['reality'].mean().to_frame().reset_index().rename({'dist':'dist','reality':'perprice'},axis=1).set_index('dist')
mean_house1

        perprice
dist
嘉定     70.873715
奉贤     28.812139
宝山     92.039816
徐汇    114.750316
普陀    113.217566
杨浦    114.002971
松江     76.199736
浦东     77.423394
虹口    128.071594
金山     22.211050
长宁    125.974384
闵行     91.824768
青浦     56.502805
静安    122.915460
黄浦    142.842902

In [16]:
#合并两表的值
house_count1['perprice'] = mean_house1['perprice']
house_count1['dist'] = house_count1.index
#添加city字段
house_count1['city'] = '1'
house_count1  #得到上海地区信息

      count    perprice dist city
dist
嘉定      186   70.873715   嘉定    1
奉贤      178   28.812139   奉贤    1
宝山      223   92.039816   宝山    1
徐汇      992  114.750316   徐汇    1
普陀      358  113.217566   普陀    1
杨浦      262  114.002971   杨浦    1
松江      187   76.199736   松江    1
浦东     1657   77.423394   浦东    1
虹口      155  128.071594   虹口    1
金山        2   22.211050   金山    1
长宁      764  125.974384   长宁    1
闵行      666   91.824768   闵行    1
青浦      206   56.502805   青浦    1
静安      557  122.915460   静安    1
黄浦      348  142.842902   黄浦    1

In [18]:
#深圳数据
city2 = df3.loc[df1['city'] == '2']
# count字段
house_count2 = city2.groupby('dist')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
house_count2 = house_count2.reset_index().rename({'dist':'dist','reality':'count'},axis=1).set_index('dist')
house_count2
#按地区排序，方便合并
house_count2.sort_values("dist",inplace=True)
house_count2

      count
dist
光明区      55
南山区     999
坪山区      88
大鹏新区     28
宝安区     728
盐田区     120
福田区     969
罗湖区     721
龙华区     665
龙岗区    1101

In [19]:
#每平米单价字段
mean_house2 = city2.groupby('dist')['reality'].mean().to_frame().reset_index().rename({'dist':'dist','reality':'perprice'},axis=1).set_index('dist')
mean_house2

        perprice
dist
光明区    53.803324
南山区   126.086612
坪山区    44.874093
大鹏新区   49.876325
宝安区    91.102358
盐田区    65.465123
福田区   127.386056
罗湖区    99.890843
龙华区    80.294512
龙岗区    70.351690

In [20]:
#合并两表的值
house_count2['perprice'] = mean_house2['perprice']
house_count2['dist'] = house_count2.index
house_count2

      count    perprice  dist
dist
光明区      55   53.803324   光明区
南山区     999  126.086612   南山区
坪山区      88   44.874093   坪山区
大鹏新区     28   49.876325  大鹏新区
宝安区     728   91.102358   宝安区
盐田区     120   65.465123   盐田区
福田区     969  127.386056   福田区
罗湖区     721   99.890843   罗湖区
龙华区     665   80.294512   龙华区
龙岗区    1101   70.351690   龙岗区

In [21]:
#添加city字段
house_count2['city'] = '2'
house_count2  #得到深圳地区信息

      count    perprice  dist city
dist
光明区      55   53.803324   光明区    2
南山区     999  126.086612   南山区    2
坪山区      88   44.874093   坪山区    2
大鹏新区     28   49.876325  大鹏新区    2
宝安区     728   91.102358   宝安区    2
盐田区     120   65.465123   盐田区    2
福田区     969  127.386056   福田区    2
罗湖区     721   99.890843   罗湖区    2
龙华区     665   80.294512   龙华区    2
龙岗区    1101   70.351690   龙岗区    2

In [22]:
house_counts = house_count1.append(house_count) #合并北京上海地区信息
house_counts

       count    perprice   dist city
dist
嘉定       186   70.873715     嘉定    1
奉贤       178   28.812139     奉贤    1
宝山       223   92.039816     宝山    1
徐汇       992  114.750316     徐汇    1
普陀       358  113.217566     普陀    1
杨浦       262  114.002971     杨浦    1
松江       187   76.199736     松江    1
浦东      1657   77.423394     浦东    1
虹口       155  128.071594     虹口    1
金山         2   22.211050     金山    1
长宁       764  125.974384     长宁    1
闵行       666   91.824768     闵行    1
青浦       206   56.502805     青浦    1
静安       557  122.915460     静安    1
黄浦       348  142.842902     黄浦    1
东城       305  125.119949     东城    0
丰台       587   94.281691     丰台    0
亦庄开发区    131   73.458337  亦庄开发区    0
大兴       428   80.267987     大兴    0
房山       214   54.910599     房山    0
昌平       263  105.605065     昌平    0
朝阳      1492  101.954125     朝阳    0
海淀       468  117.071187     海淀    0
石景山      164  100.656716    石景山    0
西城       295  126.795251     西城    0
通州       334  103.603439     通州    0
门头沟      126   70.065987    门头沟    0
顺义       499   56.309875     顺义    0

In [23]:
dist_info = house_counts.append(house_count2) #合并三个城市的信息
dist_info

       count    perprice   dist city
dist
嘉定       186   70.873715     嘉定    1
奉贤       178   28.812139     奉贤    1
宝山       223   92.039816     宝山    1
徐汇       992  114.750316     徐汇    1
普陀       358  113.217566     普陀    1
杨浦       262  114.002971     杨浦    1
松江       187   76.199736     松江    1
浦东      1657   77.423394     浦东    1
虹口       155  128.071594     虹口    1
金山         2   22.211050     金山    1
长宁       764  125.974384     长宁    1
闵行       666   91.824768     闵行    1
青浦       206   56.502805     青浦    1
静安       557  122.915460     静安    1
黄浦       348  142.842902     黄浦    1
东城       305  125.119949     东城    0
丰台       587   94.281691     丰台    0
亦庄开发区    131   73.458337  亦庄开发区    0
大兴       428   80.267987     大兴    0
房山       214   54.910599     房山    0
昌平       263  105.605065     昌平    0
朝阳      1492  101.954125     朝阳    0
海淀       468  117.071187     海淀    0
石景山      164  100.656716    石景山    0
西城       295  126.795251     西城    0
通州       334  103.603439     通州    0
门头沟      126   70.065987    门头沟    0
顺义       499   56.309875     顺义    0
光明区       55   53.803324    光明区    2
南山区      999  126.086612    南山区    2
坪山区       88   44.874093    坪山区    2
大鹏新区      28   49.876325   大鹏新区    2
宝安区      728   91.102358    宝安区    2
盐田区      120   65.465123    盐田区    2
福田区      969  127.386056    福田区    2
罗湖区      721   99.890843    罗湖区    2
龙华区      665   80.294512    龙华区    2
龙岗区     1101   70.351690    龙岗区    2

In [24]:
#转换类型，改变默认数据库表字段输入类型 
from sqlalchemy.types import VARCHAR, Float, Integer 
from sqlalchemy import create_engine
def mapping_df_types(df):
    dtypedict = {}
    for i, j in zip(df.columns, df.dtypes):
        if "object" in str(j):
            dtypedict.update({i: VARCHAR(length=255)})
        if "float" in str(j):
            dtypedict.update({i: Float(precision=2, asdecimal=True)})
        if "int" in str(j):
            dtypedict.update({i: Integer()})
    return dtypedict
dtypedict = mapping_df_types(dist_info)

#将结果插入watch0表
engine = create_engine('mysql+pymysql://root:123456789@localhost:3306/house_datas')
con = engine.connect()
dist_info.to_sql(name='watch0', 
          con=con,
          if_exists='replace', 
          index=False,
          dtype=dtypedict
         )

print('Read from and write to Mysql table successfully!')

Read from and write to Mysql table successfully!

In [25]:
#北京：根据楼层分析
count = city0.groupby('floor')['reality'].count().sort_values(ascending=True).to_frame()
count

           reality
floor
高���层（6层）        1
中楼层（3层）          1
中楼层（42层）         1
低楼层（31层）         1
高楼层��6层）         1
...            ...
高楼层（5层）        100
中楼层（5层）        211
低楼层（6层）        435
中楼层（6层）        602
高楼层（6层）        921

[115 rows x 1 columns]

In [26]:
# 修改列名称
count = count.reset_index().rename({'floor':'floor','reality':'count'},axis=1).set_index('floor')
count

           count
floor
高���层（6层）      1
中楼层（3层）        1
中楼层（42层）       1
低楼层（31层）       1
高楼层��6层）       1
...          ...
高楼层（5层）      100
中楼层（5层）      211
低楼层（6层）      435
中楼层（6层）      602
高楼层（6层）      921

[115 rows x 1 columns]

In [30]:
count['floor'] = count.index #楼层作为列名
count.sort_values("count",inplace=True,ascending=False)  #楼层数量排序，从大到小
#保留最具代表性的20个楼层
floor_count = count.head(20)
count['city'] = '0'  #添加城市属性
floor_count

          count     floor city
floor
高楼层（6层）     921   高楼层（6层）    0
中楼层（6层）     602   中楼层（6层）    0
低楼层（6层）     435   低楼层（6层）    0
中楼层（5层）     211   中楼层（5层）    0
高楼层（5层）     100   高楼层（5层）    0
高楼层（18层）     89  高楼层（18层）    0
低楼层（18层）     88  低楼层（18层）    0
中楼层（18层）     85  中楼层（18层）    0
中楼层（7层）      83   中楼层（7层）    0
高楼层（7层）      75   高楼层（7层）    0
中楼层（15层）     70  中楼层（15层）    0
低楼层（28层）     69  低楼层（28层）    0
低楼层（16层）     68  低楼层（16层）    0
中楼层（16层）     65  中楼层（16层）    0
低楼层（21层）     56  低楼层（21层）    0
中楼层（4层）      53   中楼层（4层）    0
低楼层（15层）     52  低楼层（15层）    0
高楼层（28层）     51  高楼层（28层）    0
中楼层（28层）     51  中楼层（28层）    0
中楼层（20层）     50  中楼层（20层）    0

In [31]:
#上海：根据楼层分析
count1 = city1.groupby('floor')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
count1 = count1.reset_index().rename({'floor':'floor','reality':'count'},axis=1).set_index('floor')
count1['floor'] = count1.index #楼层作为列名
count1['city'] = '1'  #添加城市属性
count1.sort_values("count",inplace=True,ascending=False)  #楼层数量排序，从大到小
#保留最具代表性的20个楼层
floor_count1 = count1.head(20)
floor_count1

          count     floor city
floor
高楼层（6层）    1204   高楼层（6层）    1
中楼层（6层）     864   中楼层（6层）    1
低楼层（6层）     555   低楼层（6层）    1
中楼层（5层）     324   中楼层（5层）    1
高楼层（7层）     164   高楼层（7层）    1
中楼层（7层）     157   中楼层（7层）    1
高楼层（5层）     140   高楼层（5层）    1
高楼层（18层）    140  高楼层（18层）    1
低楼层（18层）    139  低楼层（18层）    1
中楼层（18层）    136  中楼层（18层）    1
中楼层（11层）    109  中楼层（11层）    1
中楼层（14层）     89  中楼层（14层）    1
中楼层（17层）     87  中楼层（17层）    1
高楼层（14层）     84  高楼层（14层）    1
中楼层（8层）      83   中楼层（8层）    1
低楼层（5层）      79   低楼层（5层）    1
低楼层（3层）      63   低楼层（3层）    1
高楼层（17层）     62  高楼层（17层）    1
低楼层（7层）      61   低楼层（7层）    1
高楼层（11层）     59  高楼层（11层）    1

In [32]:
#拼接北京和上海楼层分析
floor_counts = floor_count.append(floor_count1)
floor_counts

          count     floor city
floor
高楼层（6层）     921   高楼层（6层）    0
中楼层（6层）     602   中楼层（6层）    0
低楼层（6层）     435   低楼层（6层）    0
中楼层（5层）     211   中楼层（5层）    0
高楼层（5层）     100   高楼层（5层）    0
高楼层（18层）     89  高楼层（18层）    0
低楼层（18层）     88  低楼层（18层）    0
中楼层（18层）     85  中楼层（18层）    0
中楼层（7层）      83   中楼层（7层）    0
高楼层（7层）      75   高楼层（7层）    0
中楼层（15层）     70  中楼层（15层）    0
低楼层（28层）     69  低楼层（28层）    0
低楼层（16层）     68  低楼层（16层）    0
中楼层（16层）     65  中楼层（16层）    0
低楼层（21层）     56  低楼层（21层）    0
中楼层（4层）      53   中楼层（4层）    0
低楼层（15层）     52  低楼层（15层）    0
高楼层（28层）     51  高楼层（28层）    0
中楼层（28层）     51  中楼层（28层）    0
中楼层（20层）     50  中楼层（20层）    0
高楼层（6层）    1204   高楼层（6层）    1
中楼层（6层）     864   中楼层（6层）    1
低楼层（6层）     555   低楼层（6层）    1
中楼层（5层）     324   中楼层（5层）    1
高楼层（7层）     164   高楼层（7层）    1
中楼层（7层）     157   中楼层（7层）    1
高楼层（5层）     140   高楼层（5层）    1
高楼层（18层）    140  高楼层（18层）    1
低楼层（18层）    139  低楼层（18层）    1
中楼层（18层）    136  中楼层（18层）    1
中楼层（11层）    109  中楼层（11层）    1
中楼层（14层）     89  中楼层（14层）    1
中楼层（17层）     87  中楼层（17层）    1
高楼层（14层）     84  高楼层（14层）    1
中楼层（8层）      83   中楼层（8层）    1
低楼层（5层）      79   低楼层（5层）    1
低楼层（3层）      63   低楼层（3层）    1
高楼层（17层）     62  高楼层（17层）    1
低楼层（7层）      61   低楼层（7层）    1
高楼层（11层）     59  高楼层（11层）    1

In [33]:
#深圳：根据楼层分析
count2 = city2.groupby('floor')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
count2 = count2.reset_index().rename({'floor':'floor','reality':'count'},axis=1).set_index('floor')
count2['floor'] = count2.index #楼层作为列名
count2['city'] = '2'  #添加城市属性
count2.sort_values("count",inplace=True,ascending=False)  #楼层数量排序，从大到小
#保留最具代表性的20个楼层
floor_count2 = count2.head(20)
floor_count2

          count     floor city
floor
高楼层（7层）     345   高楼层（7层）    2
中楼层（8层）     238   中楼层（8层）    2
中楼层（7层）     236   中楼层（7层）    2
高楼层（8层）     221   高楼层（8层）    2
低楼层（7层）     130   低楼层（7层）    2
低楼层（32层）    129  低楼层（32层）    2
中楼层（32层）    117  中楼层（32层）    2
高楼层（32层）    116  高楼层（32层）    2
中楼层（30层）    106  中楼层（30层）    2
中楼层（31层）     94  中楼层（31层）    2
高楼层（6层）      90   高楼层（6层）    2
低楼层（33层）     88  低楼层（33层）    2
中楼层（33层）     82  中楼层（33层）    2
低楼层（30层）     82  低楼层（30层）    2
高楼层（33层）     78  高楼层（33层）    2
低楼层（31层）     77  低楼层（31层）    2
中楼层（9层）      72   中楼层（9层）    2
高楼层（30层）     70  高楼层（30层）    2
高楼层（31层）     69  高楼层（31层）    2
中楼层（6层）      67   中楼层（6层）    2

In [34]:
#拼接三个楼层分析
floor_counts = floor_counts.append(floor_count2)
floor_counts

          count     floor city
floor
高楼层（6层）     921   高楼层（6层）    0
中楼层（6层）     602   中楼层（6层）    0
低楼层（6层）     435   低楼层（6层）    0
中楼层（5层）     211   中楼层（5层）    0
高楼层（5层）     100   高楼层（5层）    0
高楼层（18层）     89  高楼层（18层）    0
低楼层（18层）     88  低楼层（18层）    0
中楼层（18层）     85  中楼层（18层）    0
中楼层（7层）      83   中楼层（7层）    0
高楼层（7层）      75   高楼层（7层）    0
中楼层（15层）     70  中楼层（15层）    0
低楼层（28层）     69  低楼层（28层）    0
低楼层（16层）     68  低楼层（16层）    0
中楼层（16层）     65  中楼层（16层）    0
低楼层（21层）     56  低楼层（21层）    0
中楼层（4层）      53   中楼层（4层）    0
低楼层（15层）     52  低楼层（15层）    0
高楼层（28层）     51  高楼层（28层）    0
中楼层（28层）     51  中楼层（28层）    0
中楼层（20层）     50  中楼层（20层）    0
高楼层（6层）    1204   高楼层（6层）    1
中楼层（6层）     864   中楼层（6层）    1
低楼层（6层）     555   低楼层（6层）    1
中楼层（5层）     324   中楼层（5层）    1
高楼层（7层）     164   高楼层（7层）    1
中楼层（7层）     157   中楼层（7层）    1
高楼层（5层）     140   高楼层（5层）    1
高楼层（18层）    140  高楼层（18层）    1
低楼层（18层）    139  低楼层（18层）    1
中楼层（18层）    136  中楼层（18层）    1
中楼层（11层）    109  中楼层（11层）    1
中楼层（14层）     89  中楼层（14层）    1
中楼层（17层）     87  中楼层（17层）    1
高楼层（14层）     84  高楼层（14层）    1
中楼层（8层）      83   中楼层（8层）    1
低楼层（5层）      79   低楼层（5层）    1
低楼层（3层）      63   低楼层（3层）    1
高楼层（17层）     62  高楼层（17层）    1
低楼层（7层）      61   低楼层（7层）    1
高楼层（11层）     59  高楼层（11层）    1
高楼层（7层）     345   高楼层（7层）    2
中楼层（8层）     238   中楼层（8层）    2
中楼层（7层）     236   中楼层（7层）    2
高楼层（8层）     221   高楼层（8层）    2
低楼层（7层）     130   低楼层（7层）    2
低楼层（32层）    129  低楼层（32层）    2
中楼层（32层）    117  中楼层（32层）    2
高楼层（32层）    116  高楼层（32层）    2
中楼层（30层）    106  中楼层（30层）    2
中楼层（31层）     94  中楼层（31层）    2
高楼层（6层）      90   高楼层（6层）    2
低楼层（33层）     88  低楼层（33层）    2
中楼层（33层）     82  中楼层（33层）    2
低楼层（30层）     82  低楼层（30层）    2
高楼层（33层）     78  高楼层（33层）    2
低楼层（31层）     77  低楼层（31层）    2
中楼层（9层）      72   中楼层（9层）    2
高楼层（30层）     70  高楼层（30层）    2
高楼层（31层）     69  高楼层（31层）    2
中楼层（6层）      67   中楼层（6层）    2

In [35]:
#转换类型，改变默认数据库表字段输入类型 
dtypedict1 = mapping_df_types(floor_counts)

#watch1表插入指定字段数据
engine = create_engine('mysql+pymysql://root:123456789@localhost:3306/house_datas')
con = engine.connect()
floor_counts.to_sql(name='watch1', 
          con=con,
          if_exists='replace', 
          index=False,
          dtype=dtypedict1
         )

print('Read from and write to Mysql table successfully!')

Read from and write to Mysql table successfully!

In [36]:
#北京：根据户型分析
style_count = city0.groupby('style')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
style_count = style_count.reset_index().rename({'style':'style','reality':'count'},axis=1).set_index('style')
style_count['style'] = style_count.index #楼层作为列名
style_count['city'] = '0'  #添加城市属性
style_count.sort_values("count",inplace=True,ascending=False)  #楼层数量排序，从大到小
#保留最具代表性的10个布局
style_counts = style_count.head(10)
style_counts

        count   style city
style
2室1厅1卫   1708  2室1厅1卫    0
1室1厅1卫   1583  1室1厅1卫    0
1室0厅1卫    420  1室0厅1卫    0
3居室       348     3居室    0
3室1厅1卫    182  3室1厅1卫    0
1房间1卫     144   1房间1卫    0
2居室       123     2居室    0
2房间1卫      92   2房间1卫    0
4居室        65     4居室    0
2室1厅2卫     60  2室1厅2卫    0

In [37]:
#上海：根据户型分析
style_count1 = city1.groupby('style')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
style_count1 = style_count1.reset_index().rename({'style':'style','reality':'count'},axis=1).set_index('style')
style_count1['style'] = style_count1.index #楼层作为列名
style_count1['city'] = '1'  #添加城市属性
style_count1.sort_values("count",inplace=True,ascending=False)  #楼层数量排序，从大到小
#保留最具代表性的10个布局
style_counts1 = style_count1.head(10)
style_counts1

        count   style city
style
1室1厅1卫   2050  1室1厅1卫    1
2室1厅1卫   1127  2室1厅1卫    1
1室0厅1卫    819  1室0厅1卫    1
3室1厅1卫    574  3室1厅1卫    1
2室2厅1卫    423  2室2厅1卫    1
4室1厅2卫    302  4室1厅2卫    1
3室2厅2卫    203  3室2厅2卫    1
2室0厅1卫    173  2室0厅1卫    1
3室1厅2卫    162  3室1厅2卫    1
3室2厅1卫    121  3室2厅1卫    1

In [38]:
#深圳：根据户型分析
style_count2 = city2.groupby('style')['reality'].count().sort_values(ascending=True).to_frame()
# 修改列名称
style_count2 = style_count2.reset_index().rename({'style':'style','reality':'count'},axis=1).set_index('style')
style_count2['style'] = style_count2.index #楼层作为列名
style_count2['city'] = '2'  #添加城市属性
style_count2.sort_values("count",inplace=True,ascending=False)  #楼层数量排序，从大到小
#保留最具代表性的10个布局
style_counts2 = style_count2.head(10)
style_counts2

        count   style city
style
1室1厅1卫   1154  1室1厅1卫    2
1室0厅1卫    947  1室0厅1卫    2
2室1厅1卫    807  2室1厅1卫    2
3室1厅1卫    336  3室1厅1卫    2
4室1厅1卫    311  4室1厅1卫    2
4室1厅2卫    254  4室1厅2卫    2
3室2厅1卫    239  3室2厅1卫    2
2室2厅1卫    213  2室2厅1卫    2
3室2厅2卫    198  3室2厅2卫    2
5室1厅2卫    181  5室1厅2卫    2

In [39]:
#拼接三个城市户型数据
styles = style_counts.append(style_counts1)
st_counts = styles.append(style_counts2)
st_counts

        count   style city
style
2室1厅1卫   1708  2室1厅1卫    0
1室1厅1卫   1583  1室1厅1卫    0
1室0厅1卫    420  1室0厅1卫    0
3居室       348     3居室    0
3室1厅1卫    182  3室1厅1卫    0
1房间1卫     144   1房间1卫    0
2居室       123     2居室    0
2房间1卫      92   2房间1卫    0
4居室        65     4居室    0
2室1厅2卫     60  2室1厅2卫    0
1室1厅1卫   2050  1室1厅1卫    1
2室1厅1卫   1127  2室1厅1卫    1
1室0厅1卫    819  1室0厅1卫    1
3室1厅1卫    574  3室1厅1卫    1
2室2厅1卫    423  2室2厅1卫    1
4室1厅2卫    302  4室1厅2卫    1
3室2厅2卫    203  3室2厅2卫    1
2室0厅1卫    173  2室0厅1卫    1
3室1厅2卫    162  3室1厅2卫    1
3室2厅1卫    121  3室2厅1卫    1
1室1厅1卫   1154  1室1厅1卫    2
1室0厅1卫    947  1室0厅1卫    2
2室1厅1卫    807  2室1厅1卫    2
3室1厅1卫    336  3室1厅1卫    2
4室1厅1卫    311  4室1厅1卫    2
4室1厅2卫    254  4室1厅2卫    2
3室2厅1卫    239  3室2厅1卫    2
2室2厅1卫    213  2室2厅1卫    2
3室2厅2卫    198  3室2厅2卫    2
5室1厅2卫    181  5室1厅2卫    2

In [40]:
dtypedict2 = mapping_df_types(st_counts)

#watch2表插入指定字段数据
engine = create_engine('mysql+pymysql://root:123456789@localhost:3306/house_datas')
con = engine.connect()
st_counts.to_sql(name='watch2', 
          con=con,
          if_exists='replace', 
          index=False,
          dtype=dtypedict2
         )

print('Read from and write to Mysql table successfully!')

Read from and write to Mysql table successfully!